version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/postgresql/data
    environment:
      — POSTGRES_DB: app_db
      — POSTGRES_USER: postgres
      — POSTGRES_PASSWORD: postgres
